apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-hello
  namespace: surjan-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-hello
  template:
    metadata:
      labels:
        app: springboot-hello
    spec:
      containers:
      - name: springboot-hello
        image: surjan22/springboot_app:2   # 👈 matches your Docker push
        ports:
        - containerPort: 8080
